name: Git-Index CI

on:
  schedule:
    - cron:  '0 3 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v2
    - name: Install sudo package
      run: apt update && apt install sudo
    - name: Install SQLite3
      run: |
        sudo apt update
        sudo apt-get install -y sqlite3 libsqlite3-dev
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: crystal spec
    - name: Run Ameba
      run: bin/ameba
    - name: Build docs
      run: crystal docs
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
